[settings]
experimental = true

[tools]
"cargo-binstall" = "latest"

# pragma: alphabetize
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:ast-grep/ast-grep" = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:aws/aws-cli" = "2"
"aqua:carapace-sh/carapace-bin" = "latest"
"aqua:cli/cli" = "latest"
"aqua:cloudflare/cloudflared" = "latest"
"aqua:common-fate/granted" = "latest"
"aqua:direnv/direnv" = "latest"
"aqua:duckdb/duckdb" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:hashicorp/terraform" = "latest"
"aqua:hashicorp/terraform-ls" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jj-vcs/jj" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:kubernetes/kubernetes/kubectl" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:pre-commit/pre-commit" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:sbstp/kubie" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/numbat" = "latest"
"aqua:sharkdp/vivid" = "latest"
"aqua:stern/stern" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:terraform-linters/tflint" = "latest"
"aqua:x-motemen/ghq" = "latest"
"asdf:mise-plugins/mise-1password-cli" = "latest"
"asdf:mise-plugins/mise-bat-extras" = "latest"
"asdf:mise-plugins/mise-lua" = "latest"
"asdf:mise-plugins/mise-yarn" = "latest"
"cargo:atuin" = "latest"
"cargo:broot" = "latest"
"cargo:csvlens" = "latest"
"cargo:diffedit3" = "latest"
"cargo:eza" = "latest"
"cargo:harper-ls" = "latest"
"cargo:just-lsp" = "latest"
"cargo:lazyjj" = "latest"
"cargo:selene" = "latest"
"cargo:tokei" = "latest"
"deno" = "latest"
"erlang" = "latest"
"github:grafana/jsonnet-language-server" = "latest"
"go" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/google/go-jsonnet/cmd/jsonnet" = "latest"
"go:github.com/google/go-jsonnet/cmd/jsonnet-lint" = "latest"
"go:github.com/mbrt/gmailctl/cmd/gmailctl" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"node" = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@bytebase/dbhub" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@google/clasp" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:@modelcontextprotocol/server-memory" = "latest"
"npm:@modelcontextprotocol/server-sequential-thinking" = "latest"
"npm:@opentofu/opentofu-mcp-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@upstash/context7-mcp" = "latest"
"npm:bash-language-server" = "latest"
"npm:eslint_d" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:mcp-hub" = "latest"
"npm:mcp-remote" = "latest"
"npm:opencode-ai" = "latest"
"npm:prettier" = "latest"
"npm:shadcn" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:asciinema" = "latest"
"pipx:basedpyright" = "latest"
"pipx:chromadb" = "0.6.3"
"pipx:debugpy" = "latest"
"pipx:git+https://github.com/neongreen/jj-run.git" = "latest"
"pipx:git+https://github.com/oraios/serena.git" = "9cf5ee2"
"pipx:harlequin" = { version = "latest", extras = "postgres,s3" }
"pipx:invoke" = "latest"
"pipx:jj-pre-push" = "latest"
"pipx:litecli" = "latest"
"pipx:pgcli" = "latest"
"pipx:pyrefly" = "latest"
"pipx:sort-lines" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:ty" = "latest"
"pipx:vectorcode" = { version = "latest", extras = "lsp,mcp" }
"pipx:zuban" = "latest"
"prek" = "latest"
"python" = "latest"
"ubi:TomWright/dasel" = "latest"
"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:casey/just" = "latest"
"ubi:dandavison/delta" = "latest"
"ubi:denisidoro/navi" = "2.23.0"
"ubi:getsops/sops" = "latest"
"ubi:hmarr/codeowners" = "latest"
"ubi:houseabsolute/ubi" = "latest"
"ubi:idursun/jjui" = "latest"
"ubi:jdx/usage" = "latest"
"ubi:koalaman/shellcheck" = "latest"
"ubi:sharkdp/bat" = "latest"
"ubi:supabase-community/postgres-language-server" = { version = "latest", exe = "postgrestools" }
"ubi:tamasfe/taplo" = "latest"
"ubi:xo/usql" = "latest"
"ubi:zellij-org/zellij" = "latest"
